// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "oldme-api/internal/logic/admin"
	_ "oldme-api/internal/logic/middleware"
)
