// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "oldme-api/internal/logic/account"
	_ "oldme-api/internal/logic/admin"
	_ "oldme-api/internal/logic/article"
	_ "oldme-api/internal/logic/article-grp"
	_ "oldme-api/internal/logic/file"
	_ "oldme-api/internal/logic/middleware"
)
