// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package reading

import (
	"github.com/oldme-git/oldme-api/api/reading"
)

type ControllerV1 struct{}

func NewV1() reading.IReadingV1 {
	return &ControllerV1{}
}
