// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// ArticleGroup is the golang structure of table article_group for DAO operations like Where/Data.
type ArticleGroup struct {
	g.Meta `orm:"table:article_group, do:true"`
	Id     interface{} //
	Name   interface{} // 名称
	Onshow interface{} // 是否显示
}
