// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sentence

import (
	"github.com/oldme-git/oldme-api/api/sentence"
)

type ControllerV1 struct{}

func NewV1() sentence.ISentenceV1 {
	return &ControllerV1{}
}
