// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"oldme-api/internal/model"
)

type IAdmin interface {
	Create(ctx context.Context, in model.AdminCreateInput) (err error)
	Update(ctx context.Context)
	Read(ctx context.Context)
	Del(ctx context.Context)
}

var localAdmin IAdmin

func Admin() IAdmin {
	if localAdmin == nil {
		panic("implement not found for interface IAdmin, forgot register?")
	}
	return localAdmin
}

func RegisterAdmin(i IAdmin) {
	localAdmin = i
}
