// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/oldme-git/oldme-api/internal/model"
	"github.com/oldme-git/oldme-api/internal/model/entity"
)

type (
	IArticle interface {
		Cre(ctx context.Context, in *model.ArticleInput) (lastId model.Id, err error)
		Upd(ctx context.Context, id model.Id, in *model.ArticleInput) (err error)
		List(ctx context.Context, query *model.ArticleQuery) (list []entity.Article, total uint, err error)
		Show(ctx context.Context, id model.Id) (info *entity.Article, err error)
		Del(ctx context.Context, id model.Id, isReal bool) (err error)
		ReCre(ctx context.Context, id model.Id) (err error)
		Hist(ctx context.Context, id model.Id) (err error)
		UpdLastedAt(ctx context.Context, id model.Id) (err error)
		IsExist(ctx context.Context, id model.Id) bool
	}
)

var (
	localArticle IArticle
)

func Article() IArticle {
	if localArticle == nil {
		panic("implement not found for interface IArticle, forgot register?")
	}
	return localArticle
}

func RegisterArticle(i IArticle) {
	localArticle = i
}
