// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"oldme-api/internal/model"
	"oldme-api/internal/model/entity"
)

type IArticleGrp interface {
	Cre(ctx context.Context, in *model.ArticleGrpInput) (err error)
	Upd(ctx context.Context, id uint, in *model.ArticleGrpInput) (err error)
	Del(ctx context.Context, id uint) (err error)
	List(ctx context.Context) (list *model.ArticleGrpList, err error)
	Show(ctx context.Context, id uint) (info *entity.ArticleGrp, err error)
	IsExist(ctx context.Context, id uint) bool
}

var localArticleGrp IArticleGrp

func ArticleGrp() IArticleGrp {
	if localArticleGrp == nil {
		panic("implement not found for interface IArticleGrp, forgot register?")
	}
	return localArticleGrp
}

func RegisterArticleGrp(i IArticleGrp) {
	localArticleGrp = i
}
