// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"oldme-api/internal/model"
)

type IArticle interface {
	Cre(ctx context.Context, in *model.ArticleInput) (err error)
}

var localArticle IArticle

func Article() IArticle {
	if localArticle == nil {
		panic("implement not found for interface IArticle, forgot register?")
	}
	return localArticle
}

func RegisterArticle(i IArticle) {
	localArticle = i
}
