// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"oldme-api/internal/model"
	"oldme-api/internal/model/entity"
)

type (
	IArticleGrp interface {
		Cre(ctx context.Context, in *model.ArticleGrpInput) (err error)
		Upd(ctx context.Context, id model.Id, in *model.ArticleGrpInput) (err error)
		Del(ctx context.Context, id model.Id) (err error)
		List(ctx context.Context) (list *[]entity.ArticleGrp, err error)
		Show(ctx context.Context, id model.Id) (info *entity.ArticleGrp, err error)
		IsExist(ctx context.Context, id model.Id) bool
	}
)

var (
	localArticleGrp IArticleGrp
)

func ArticleGrp() IArticleGrp {
	if localArticleGrp == nil {
		panic("implement not found for interface IArticleGrp, forgot register?")
	}
	return localArticleGrp
}

func RegisterArticleGrp(i IArticleGrp) {
	localArticleGrp = i
}
