// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"oldme-api/internal/model"

	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	IFile interface {
		Upload(ctx context.Context, file *ghttp.UploadFile) (info *model.FileInfo, err error)
		MoveTmp(ctx context.Context, dir string, file string) (info *model.FileInfo, err error)
		GetConf(ctx context.Context) (upload map[string]string, err error)
		GetPath(ctx context.Context, srcDir string) string
		GetUrl(ctx context.Context, dir string, file string) string
	}
)

var (
	localFile IFile
)

func File() IFile {
	if localFile == nil {
		panic("implement not found for interface IFile, forgot register?")
	}
	return localFile
}

func RegisterFile(i IFile) {
	localFile = i
}
