// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"oldme-api/internal/model"

	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	IFile interface {
		Upload(ctx context.Context, file *ghttp.UploadFile) (info *model.FileInfo, err error)
		Save(ctx context.Context, src string, lib string) (info *model.FileInfo, err error)
		SaveImg(ctx context.Context, src string) (info *model.FileInfo, err error)
	}
)

var (
	localFile IFile
)

func File() IFile {
	if localFile == nil {
		panic("implement not found for interface IFile, forgot register?")
	}
	return localFile
}

func RegisterFile(i IFile) {
	localFile = i
}
