// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"oldme-api/internal/model"
	"oldme-api/internal/model/entity"
)

type ILink interface {
	Cre(ctx context.Context, in *model.LinkInput) (err error)
	Upd(ctx context.Context, id uint, in *model.LinkInput) (err error)
	Del(ctx context.Context, id uint) (err error)
	List(ctx context.Context) (list *[]entity.Link, err error)
}

var localLink ILink

func Link() ILink {
	if localLink == nil {
		panic("implement not found for interface ILink, forgot register?")
	}
	return localLink
}

func RegisterLink(i ILink) {
	localLink = i
}
