// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/oldme-git/oldme-api/internal/model"
	"github.com/oldme-git/oldme-api/internal/model/entity"
)

type (
	ILink interface {
		Cre(ctx context.Context, in *model.LinkInput) (err error)
		Upd(ctx context.Context, id model.Id, in *model.LinkInput) (err error)
		Del(ctx context.Context, id model.Id) (err error)
		List(ctx context.Context) (list []entity.Link, err error)
	}
)

var (
	localLink ILink
)

func Link() ILink {
	if localLink == nil {
		panic("implement not found for interface ILink, forgot register?")
	}
	return localLink
}

func RegisterLink(i ILink) {
	localLink = i
}
