// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"oldme-api/internal/model"
	"oldme-api/internal/model/entity"
)

type (
	IReply interface {
		Cre(ctx context.Context, in *model.ReplyInput) (err error)
		Upd(ctx context.Context, id model.Id, in *model.ReplyInput) (err error)
		Del(ctx context.Context, id model.Id) (err error)
		List(ctx context.Context, query *model.ReplyQuery) (list *[]entity.Reply, total uint, err error)
		Show(ctx context.Context, id model.Id) (info *model.ReplyShow, err error)
		Check(ctx context.Context, id model.Id, result bool, reasonSlice ...string) error
	}
)

var (
	localReply IReply
)

func Reply() IReply {
	if localReply == nil {
		panic("implement not found for interface IReply, forgot register?")
	}
	return localReply
}

func RegisterReply(i IReply) {
	localReply = i
}
