// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
)

type IRich interface {
	Save(ctx context.Context, text *string)
	Edit(ctx context.Context, oldText *string, newText *string)
	Del(ctx context.Context, text *string) (err error)
}

var localRich IRich

func Rich() IRich {
	if localRich == nil {
		panic("implement not found for interface IRich, forgot register?")
	}
	return localRich
}

func RegisterRich(i IRich) {
	localRich = i
}
