// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"oldme-api/internal/model/entity"
)

type ISaying interface {
	Cre(ctx context.Context, saying string) (err error)
	Upd(ctx context.Context, id uint, saying string) (err error)
	Del(ctx context.Context, id uint) (err error)
	List(ctx context.Context) (list *[]entity.Saying, err error)
	Show(ctx context.Context) (saying string, err error)
}

var localSaying ISaying

func Saying() ISaying {
	if localSaying == nil {
		panic("implement not found for interface ISaying, forgot register?")
	}
	return localSaying
}

func RegisterSaying(i ISaying) {
	localSaying = i
}
