// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/oldme-git/oldme-api/internal/model"
	"github.com/oldme-git/oldme-api/internal/model/entity"
)

type (
	ISaying interface {
		Cre(ctx context.Context, saying string) (err error)
		Upd(ctx context.Context, id model.Id, saying string) (err error)
		Del(ctx context.Context, id model.Id) (err error)
		List(ctx context.Context) (list []entity.Saying, err error)
		Show(ctx context.Context) (saying string, err error)
	}
)

var (
	localSaying ISaying
)

func Saying() ISaying {
	if localSaying == nil {
		panic("implement not found for interface ISaying, forgot register?")
	}
	return localSaying
}

func RegisterSaying(i ISaying) {
	localSaying = i
}
