// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tag_grp

import (
	"github.com/oldme-git/oldme-api/api/tag_grp"
)

type ControllerV1 struct{}

func NewV1() tag_grp.ITagGrpV1 {
	return &ControllerV1{}
}
