// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tag

import (
	"github.com/oldme-git/oldme-api/api/tag"
)

type ControllerV1 struct{}

func NewV1() tag.ITagV1 {
	return &ControllerV1{}
}
