// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Admin is the golang structure for table admin.
type Admin struct {
	Id        uint        `json:"id"        description:""`
	Username  string      `json:"username"  description:"用户名"`
	Password  string      `json:"password"  description:"密码"`
	LastLogin *gtime.Time `json:"lastLogin" description:"最后登录时间"`
}
