// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ArticleGroup is the golang structure for table article_group.
type ArticleGroup struct {
	Id     uint   `json:"id"     description:""`
	Name   string `json:"name"   description:"名称"`
	Onshow uint   `json:"onshow" description:"是否显示"`
}
