// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Saying is the golang structure for table saying.
type Saying struct {
	Id     uint   `json:"id"     description:""`
	Saying string `json:"saying" description:""`
}
